config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'

  resources :projects, except: :destroy
  resources :speaking_engagements, only: %i[new create update edit]

  get '/about', to: 'about#show', as: 'about'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  get '/admin', to: 'sessions#new'
  post '/admin', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: 'destroy_session'

  get '/favorites', to: 'posts#favorites', as: 'favorite_posts'
  get '/:url_slug', to: 'posts#show', as: 'post', param: :url_slug
  get '/:url_slug/edit', to: 'posts#edit', as: 'edit_post', param: :url_slug
  patch '/:url_slug', to: 'posts#update', param: :url_slug

  get '/posts/new', to: 'posts#new', as: 'new_post'
  post '/posts/new', to: 'posts#create', as: 'posts'

  post '/body_preview/', to: 'posts#body_preview'
  post '/slug_preview/', to: 'posts#slug_preview'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates_presence_of :title, :description, :hyperlink
  scope :featured, -> { where('featured_order is not null') }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  helper_attr_accessor :project, :projects

  before_action :require_developer
  before_action :set_project, only: %i[edit update]

  def new
    self.project = Project.new
  end

  def update
    if project.update(project_params)
      redirect_to '/about', notice: 'Project updated'
    else
      flash.now[:notice] = project.errors.full_messages
      render :edit
    end
  end

  def create
    self.project = Project.new(project_params)
    if project.save
      redirect_to '/about', notice: 'Project created'
    else
      flash.now[:notice] = project.errors.full_messages
      render :new
    end
  end

  def index
    self.projects = Project.order(:featured_order)
  end

  private

  def set_project
    self.project = Project.find_by_id!(params[:id])
  end

  def project_params
    params.require(:project).permit :title, :body, :description, :featured_order, :hyperlink
  end
end

app/views/projects/_form.html.haml
= form_for project do |f|
  %p= f.label :title
  %p= f.text_field :title
  %p= f.label :hyperlink
  %p= f.text_field :hyperlink
  %p= f.label :description
  %p= f.text_area :description
  %p= f.label :featured_order
  %p= f.text_field :featured_order
  %p= f.submit 'Submit'

app/views/projects/_projects.html.haml
%li.project
  = link_to project.title, project.hyperlink
  - if developer_signed_in?
    = link_to '[edit]', edit_project_path(project)
  %em
    = markdown_render(project.description)

app/views/projects/edit.html.haml
#posts-edit
  .page-header
    %h3 Edit Project

  = render 'form'

app/views/projects/index.html.haml
#projects-index
  .page-header
    %h3 Projects

  - projects.each do |project|
    = render 'projects', project: project

app/views/projects/new.html.haml
#projects-new
  .page-header
    %h3 Create Project

  = render 'form'