config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'

  resources :projects, except: :destroy
  resources :speaking_engagements, only: %i[new create update edit]

  get '/about', to: 'about#show', as: 'about'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  get '/admin', to: 'sessions#new'
  post '/admin', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: 'destroy_session'

  get '/favorites', to: 'posts#favorites', as: 'favorite_posts'
  get '/:url_slug', to: 'posts#show', as: 'post', param: :url_slug
  get '/:url_slug/edit', to: 'posts#edit', as: 'edit_post', param: :url_slug
  patch '/:url_slug', to: 'posts#update', param: :url_slug

  get '/posts/new', to: 'posts#new', as: 'new_post'
  post '/posts/new', to: 'posts#create', as: 'posts'

  post '/body_preview/', to: 'posts#body_preview'
  post '/slug_preview/', to: 'posts#slug_preview'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates_presence_of :body
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_uniqueness_of :url_slug

  scope :ordered, -> { order('created_at desc') }

  before_create :generate_url_slug

  def to_param
    url_slug
  end

  def self.slugify(title)
    title.downcase.tr(' ', '-').gsub(/[^a-z0-9-]/, '')
  end

  def one_year_or_older?
    created_at < 1.year.ago
  end

  def anniversary?
    today = Date.today

    created_at.month == today.month &&
      created_at.day == today.day &&
      !created_at.today?
  end

  private

  def generate_url_slug
    self.url_slug = Post.slugify(title) if url_slug.nil? || url_slug.empty?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  helper_attr_accessor :older_posts, :latest_posts

  before_action :set_post_or_redirect, only: %i[show edit update]
  before_action :require_developer, except: %i[index show favorites]

  def new
    @post = Post.new
  end

  def body_preview
    render layout: false
  end

  def slug_preview
    render layout: false
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      TwitterStatus.new(@post).post_status_to_twitter
      redirect_to @post, notice: 'Post created'
    else
      flash.now[:notice] = @post.errors.full_messages
      render :new
    end
  end

  def index
    @posts = Post.ordered.page(params[:page]).per(ENV.fetch('pagination_breakpoint'))
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated'
    else
      flash.now[:notice] = @post.errors.full_messages
      render :edit
    end
  end

  def favorites
    @posts = Post.favorites.ordered.page(params[:page]).per(ENV.fetch('pagination_breakpoint'))
    render :index
  end

  private

  def post_params
    params.require(:post).permit :title, :body, :url_slug, :favorite
  end

  def set_post_or_redirect
    @post = Post.find_by_url_slug!(params[:url_slug])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
  EMOJIS = {
    lake:     '&#x2631;',
    fire:     '&#x2632;',
    thunder:  '&#x2633;',
    wind:     '&#x2634;',
    water:    '&#x2635;',
    mountain: '&#x2636;',
    earth:    '&#x2637;',
    heaven:   '&#x2630;'
  }.freeze

  def emoji_of_the_day
    content_tag(:span, emoji_of_the_day_pair[:emoji], title: emoji_of_the_day_pair[:title])
  end

  def preceding_post(post)
    post_ids = Post.ordered.pluck(:id)
    post_index = post_ids.index(post.id)
    Post.find_by_id(post_ids[post_index + 1])
  end

  def succeeding_post(post)
    post_ids = Post.ordered.pluck(:id)
    post_index = post_ids.index(post.id)
    Post.find_by_id(post_ids[post_index - 1]) unless post_index.zero?
  end

  private

  def emoji_of_the_day_pair
    today = Date.today.wday
    { title: EMOJIS.keys[today], emoji: CGI.unescapeHTML(EMOJIS.values[today]) }
  end
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  %p= f.label :title
  %p= f.text_field :title, placeholder: 'Enter title...'
  %p= f.label :url_slug, 'URL slug (leave blank to autogenerate)'
  %p= f.text_field :url_slug, placeholder: 'Enter URL slug...'
  %p= f.label :body
  %p= f.text_area :body, placeholder: 'Enter body...'
  %p= f.label :favorite
  %p= f.check_box :favorite

  .page-header
    %h3.title_preview
    .slug_preview
  %article.content

  %p= f.submit 'Submit'

app/views/posts/body_preview.html.haml
= find_and_preserve markdown_render params[:body]

app/views/posts/edit.html.haml
#posts-edit
  .page-header
    %h3 Edit Post

  = render 'form'

app/views/posts/index.html.haml
= content_for :head, auto_discovery_link_tag(:atom, root_path(format: 'atom'))

#posts-index
  .page-header
    %h3 Blog
    %p
      My
      = link_to 'favorite', favorite_posts_path
      posts are marked with
      = succeed '.' do
        = emoji_of_the_day

  %ul
    - @posts.each do |post|
      %li
        %p{ class: ('favorite' if post.favorite?) }
          - if post.favorite?
            = emoji_of_the_day
          = link_to post.title, post_path(post.url_slug)
          = post.display_date
          - if developer_signed_in?
            = link_to '[edit]', edit_post_path(post.url_slug)

  %nav
    = link_to_next_page @posts, '&#8592; Older Posts'.html_safe
    = link_to_previous_page @posts, 'Newer Posts &#8594;'.html_safe

app/views/posts/new.html.haml
#post-new
  .page-header
    %h3 Create Post

  = render 'form'

app/views/posts/preview.html.haml
= find_and_preserve markdown_render params[:body]

app/views/posts/show.html.haml
- content_for :page_title, @post.title

- content_for :canonical do
  %link{ rel: 'canonical', href: post_url(@post) }

#posts-show
  .page-header
    %h3
      - if @post.favorite?
        = emoji_of_the_day
      = @post.title


  - if developer_signed_in?
    = link_to '[edit]', edit_post_path(@post.url_slug)

  .content
    - if @post.one_year_or_older?
      %em Note: any code contained in this post is more than a year old. Please use at your own risk.

    %p= find_and_preserve markdown_render @post.body
    %p= @post.display_date


  %nav
    - preceding  = preceding_post(@post)
    - succeeding = succeeding_post(@post)
    - if preceding
      = link_to "&#8592; #{preceding.title}".html_safe, preceding
      - if succeeding
        \::
    - if succeeding
      = link_to "#{succeeding.title} &#8594;".html_safe, succeeding

app/views/posts/slug_preview.html.haml
= Post.slugify(params[:title])