config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'

  resources :projects, except: :destroy
  resources :speaking_engagements, only: %i[new create update edit]

  get '/about', to: 'about#show', as: 'about'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  get '/admin', to: 'sessions#new'
  post '/admin', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: 'destroy_session'

  get '/favorites', to: 'posts#favorites', as: 'favorite_posts'
  get '/:url_slug', to: 'posts#show', as: 'post', param: :url_slug
  get '/:url_slug/edit', to: 'posts#edit', as: 'edit_post', param: :url_slug
  patch '/:url_slug', to: 'posts#update', param: :url_slug

  get '/posts/new', to: 'posts#new', as: 'new_post'
  post '/posts/new', to: 'posts#create', as: 'posts'

  post '/body_preview/', to: 'posts#body_preview'
  post '/slug_preview/', to: 'posts#slug_preview'
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  helper_attr_accessor :links, :projects, :speaking_engagements

  def show
    self.links = JSON.parse(File.read(Rails.root.join('app', 'assets', 'links.json')))
    self.projects = Project.featured.order(:featured_order)
    self.speaking_engagements = SpeakingEngagementDecorator.decorate_collection(SpeakingEngagement.by_date)
  end
end

app/views/about/show.html.haml
- content_for :page_title, 'About'

.page-header
  %h3 About
  %p
    Technology is my passion. I'm currently excited about React.js, TypeScript,
    Elixir, Phoenix, Ruby, Rails, PostreSQL, Vim, and automated tests.

.container
  .col-md-8
    .content
      %h4= link_to_if(developer_signed_in?, 'Projects', projects_path)
      - if projects.any?
        %ul
          - projects.each do |project|
            = render 'projects/projects', project: project
      - else
        None.

    - if speaking_engagements.any?
      .content
        %h4 Talks

        .featured-video
          .embed-responsive.embed-responsive-16by9
            %iframe(width="560" height="315" src="https://www.youtube.com/embed/dwphyQmD6n8" allowfullscreen)
          .caption
            %em Format Your Elixir Code Now,
            ElixirDaze, March 2018.

        .featured-video
          .embed-responsive.embed-responsive-16by9
            %iframe(width="560" height="315" src="https://www.youtube.com/embed/D9awDBUQvr4" allowfullscreen)
          .caption
            %em Observing Change: A Gold Master Test in Practice,
            RailsConf, April 2017.

        %ul#talks
          - speaking_engagements.each do |engagement|
            %li
              = succeed ',' do
                %em= engagement.display_title
              = succeed ',' do
                = engagement.location
              = succeed '.' do
                = engagement.date.strftime('%B %Y')
              - if engagement.video_hyperlink?
                = link_to('(video)', engagement.video_hyperlink)
              - if engagement.slides_hyperlink?
                = link_to('(slides)', engagement.slides_hyperlink)
              - if developer_signed_in?
                = link_to '[edit]', edit_speaking_engagement_path(engagement)

    .content
      %h4 Other Stuff
      %ul
        - links.map do |link|
          %li
            = succeed ':' do
              = link_to link["label"], link["url"], target: '_blank', rel: "noopener noreferrer"
            = link["description"]