config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'

  resources :projects, except: :destroy
  resources :speaking_engagements, only: %i[new create update edit]

  get '/about', to: 'about#show', as: 'about'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  get '/admin', to: 'sessions#new'
  post '/admin', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: 'destroy_session'

  get '/favorites', to: 'posts#favorites', as: 'favorite_posts'
  get '/:url_slug', to: 'posts#show', as: 'post', param: :url_slug
  get '/:url_slug/edit', to: 'posts#edit', as: 'edit_post', param: :url_slug
  patch '/:url_slug', to: 'posts#update', param: :url_slug

  get '/posts/new', to: 'posts#new', as: 'new_post'
  post '/posts/new', to: 'posts#create', as: 'posts'

  post '/body_preview/', to: 'posts#body_preview'
  post '/slug_preview/', to: 'posts#slug_preview'
end

app/views/layouts/application.html.haml
!!!
%html(lang='en-US')
  = render 'shared/head'

  %body
    .jumbotron
      .container
        %h1= link_to 'Jake Worth', root_path
        %ul
          %li= link_to "Blog", root_path
          %li= link_to "About", about_path

  %main
    .container
      - if flash.present? && flash[:notice]
        .alert= [flash[:notice]].flatten.join('; ').downcase.capitalize
      .col-md-9
        = yield
      .col-md-3
        .well
          Hi! I'm Jake Worth, a developer at
          = succeed ', ' do
            = link_to "Hashrocket", "https://hashrocket.com/", target: '_blank', rel: "noopener noreferrer"
          based in Chicago. Read my
          = succeed ', ' do
            = link_to "blog", '/'
          learn
          = link_to "about", '/about'
          my work, follow me on
          = link_to "Twitter", "https://twitter.com/jwworth", target: '_blank', rel: "noopener noreferrer"
          and
          = succeed ', ' do
            = link_to "Github", "https://github.com/jwworth", target: '_blank', rel: "noopener noreferrer"
          = succeed '.' do
            = link_to "get in touch", 'mailto:' + ENV.fetch('contact_email')

        %a(class="twitter-timeline" data-tweet-limit=3 href="https://twitter.com/jwworth")
          Tweets by @jwworth

  .container
    %footer
      This blog is
      = link_to 'open source.', 'http://github.com/jwworth/jakeworth.com'
      Have a fantastic
      #{Date.today.strftime('%A')}!
      %br
      %br
      - if developer_signed_in?
        .btn-group{role: "group", "aria-label": "..."}
          = link_to 'Logout', destroy_session_path, class: 'btn btn-default'
          = link_to 'New Post', new_post_path, class: 'btn btn-default'
          = link_to 'New Project', new_project_path, class: 'btn btn-default'
          = link_to 'New Speaking Engagement', new_speaking_engagement_path, class: 'btn btn-default'

  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>